;
; for Production environment (sample)
; Replace the config.ini file with this file when deploying to a production environment.
;

[app]
name = shakeFlat - Production
initial = "S"
url = http://127.0.0.1/
company = "SHAKEFLAT";
company_link = "http://shakeflat.com";

[config]
debug_mode = false                      ; Determines whether to debug mode. Be sure to set it to false in the production environment.
display_error = true                    ; Choose whether to display errors on the screen.
jscss_version = 100                     ; If the js/css files are updated, increase this value.
php_timezone = Asia/Seoul               ; Time zone to be used by the app
main_page = welcome/main                ; start page
server_name = "Production"
translation = false                     ; Whether to use translation. If it is false, the translation file is not loaded.
default_language = "en"

[display_error]
tracing = true                          ; Whether to display tracing log message. It is recommended to set it to false in the production environment.
database = true                         ; Whether to display database error information with SQL statements. It is recommended to set it to false in the production environment.

[path]
modules = sample/modules
templates = sample/templates/admin
models = sample/models
datatables = sample/datatables
storage = sample/storage
translation_file = sample/translation.json

[storage]
check_storage = false                   ; Whether to check the storage (existence, R+W permission) It is recommended to set it to false in a production environment.
upload_path = upload                    ; It is a sub-path of storage_path.
log_path = log                          ; It is a sub-path of storage_path.
translation_cache = trans_cache         ; Cache paths for translation files

[log]
timezone = Asia/Seoul                   ; Time zone to be recorded in log
json_format = false                     ; Whether to write log contents in json format. If false, string format is used.
delimiter = \t                          ; In the case of string format, a value that separates each item. \t uses the tab character.
include_parameter = true                ; Whether to add parameter information. Applies only when using L class.
include_trace = true                    ; Whether to add trace information. Applies only when using L class.
trace_short = false                     ; Whether to log only summary information when logging trace infomation (only filename:line)
include_query = true                    ; Record all used query statements. Applies only when using L class.
query_logging = false                   ; The used query statement is left as a separate log.
log_retention_days = 30                 ; The number of days to keep the log. If it is 0, it is not deleted.

[cookie]
name = sf                               ; Defines the cookie variable name to use in the project.
expire_age = 3600                       ; time left to expiration. set in seconds

[auth]
expire_age = 3600                       ; How long the login stays(seconds). If it is a production environment, set it short.

[auth:cookie]
cookie_name = sfa                       ; When authentication is performed using shakeFlat\core\AuthCookie, the name of the cookie is defined.

[auth:session]
session_name = sfass                    ; Name to be used as key in session for auth
                                        ; It is also used as the name of the session key stored in the cookie, so do not make it the same as the name of the cookie.
session_redis = false                   ; Whether to use redis as the session storage handler
session_path = session                  ; Path to save session.
                                        ; It is located just below the storage.
                                        ; If the path starts with "/", it means a path below the root of the file system.
                                        ; If session_redis is set to true, write the redis access path. ex) tcp://127.0.0.1:6379
check_path = false                      ; Whether to check the session_path (existence, R+W permission) It is recommended to set it to false in a production environment.

[aes256]
; Defines the key required for the aes256 encryption used by the cookie or somethings.
; 32byte hexadecimal: 12345678901234567890123456789012
key_with_client     = 0123456789abcdef0123456789abcdef      ; It is a key used jointly with the client (frontend/mobile app).
iv_with_client      = 0000000000000000
key_only_server     = fedcba9876543210fedcba9876543210      ; This key is used only within the server.
iv_only_server      = 0000000000000000

[database:common]
timezone = +09:00                       ; Time zone to use in DB. Since the TZ name table required for timezone setting does not exist in rds of AWS, it is indicated as UTC offset.
mysql_charset = utf8
connect_timeout = 5                     ; database connect response latency (seconds)

[database:connection]
; Information about database connections.
; When accessing the db, "default" item information is used unless otherwise specified.
; Connection information is defined in the form of [connection_name].[index].[variable_name]
; [index] is used when there are multiple end points in cluster configuration, etc. Ex) Multiple slave db without load balancer.
; If there is more than one [index], one of several [index] will be randomly selected and used.
; If a common item is not defined in each connection, the common definition item defined above is used.
default.0.timezone = +09:00
default.0.mysql_charset = utf8
default.0.connect_timeout = 5
default.0.dsn = "mysql:host=localhost;dbname=shakeflat;"
default.0.user = shakeflat
default.0.passwd = shakeflat-password

slave.0.dsn = "mysql:host=172.0.0.1;dbname=shakeflat;"
slave.0.user = shakeflat
slave.0.passwd = shakeflat-password

slave.1.dsn = "mysql:host=172.0.0.2;dbname=shakeflat;"
slave.1.user = shakeflat
slave.1.passwd = shakeflat-password

[font_loader]
; 사용할 웹폰트 지정 (키 값을 추가하여 사용)
use_webfonts[] = "Pretendard GOV"
;use_webfonts[] = "Nanum Gothic"
;use_webfonts[] = "Oswald"
;use_webfonts[] = "Schibsted Grotesk"

; 사용할 아이콘 폰트 지정
use_iconfonts[] = "fontawesome"
use_iconfonts[] = "bootstrap-icons"


; --- 사용 가능한 폰트 및 아이콘 목록 정의 ---
[webfont:Pretendard GOV]
preload = true
face.0.family = "Pretendard GOV Variable"
face.0.weight = "45 920"
face.0.style = "normal"
face.0.display = "swap"
face.0.src.0.url = "/assets/fonts/PretendardGOV-1.3.9/PretendardGOVVariable.woff2"
face.0.src.0.format = "woff2-variations"

[webfont:Nanum Gothic]
preload = false
face.0.family = "Nanum Gothic"
face.0.style = "normal"
face.0.weight = "400"
face.0.display = "swap"
face.0.src.0.url = "/assets/fonts/nanum-gothic-v21-latin_korean/nanum-gothic-v21-latin_korean-regular.eot"
face.0.src.1.url = "/assets/fonts/nanum-gothic-v21-latin_korean/nanum-gothic-v21-latin_korean-regular.eot?#iefix"
face.0.src.1.format = "embedded-opentype"
face.0.src.2.url = "/assets/fonts/nanum-gothic-v21-latin_korean/nanum-gothic-v21-latin_korean-regular.woff2"
face.0.src.2.format = "woff2"
face.0.src.3.url = "/assets/fonts/nanum-gothic-v21-latin_korean/nanum-gothic-v21-latin_korean-regular.woff"
face.0.src.3.format = "woff"
face.0.src.4.url = "/assets/fonts/nanum-gothic-v21-latin_korean/nanum-gothic-v21-latin_korean-regular.ttf"
face.0.src.4.format = "truetype"
face.0.src.5.url = "/assets/fonts/nanum-gothic-v21-latin_korean/nanum-gothic-v21-latin_korean-regular.svg#NanumGothic"
face.0.src.5.format = "svg"

face.1.family = "Nanum Gothic"
face.1.style = "normal"
face.1.weight = "700"
face.1.display = "swap"
face.1.src.0.url = "/assets/fonts/nanum-gothic-v21-latin_korean/nanum-gothic-v21-latin_korean-700.eot"
face.1.src.1.url = "/assets/fonts/nanum-gothic-v21-latin_korean/nanum-gothic-v21-latin_korean-700.eot?#iefix"
face.1.src.1.format = "embedded-opentype"
face.1.src.2.url = "/assets/fonts/nanum-gothic-v21-latin_korean/nanum-gothic-v21-latin_korean-700.woff2"
face.1.src.2.format = "woff2"
face.1.src.3.url = "/assets/fonts/nanum-gothic-v21-latin_korean/nanum-gothic-v21-latin_korean-700.woff"
face.1.src.3.format = "woff"
face.1.src.4.url = "/assets/fonts/nanum-gothic-v21-latin_korean/nanum-gothic-v21-latin_korean-700.ttf"
face.1.src.4.format = "truetype"
face.1.src.5.url = "/assets/fonts/nanum-gothic-v21-latin_korean/nanum-gothic-v21-latin_korean-700.svg#NanumGothic"
face.1.src.5.format = "svg"

face.2.family = "Nanum Gothic"
face.2.style = "normal"
face.2.weight = "800"
face.2.display = "swap"
face.2.src.0.url = "/assets/fonts/nanum-gothic-v21-latin_korean/nanum-gothic-v21-latin_korean-800.eot"
face.2.src.1.url = "/assets/fonts/nanum-gothic-v21-latin_korean/nanum-gothic-v21-latin_korean-800.eot?#iefix"
face.2.src.1.format = "embedded-opentype"
face.2.src.2.url = "/assets/fonts/nanum-gothic-v21-latin_korean/nanum-gothic-v21-latin_korean-800.woff2"
face.2.src.2.format = "woff2"
face.2.src.3.url = "/assets/fonts/nanum-gothic-v21-latin_korean/nanum-gothic-v21-latin_korean-800.woff"
face.2.src.3.format = "woff"
face.2.src.4.url = "/assets/fonts/nanum-gothic-v21-latin_korean/nanum-gothic-v21-latin_korean-800.ttf"
face.2.src.4.format = "truetype"
face.2.src.5.url = "/assets/fonts/nanum-gothic-v21-latin_korean/nanum-gothic-v21-latin_korean-800.svg#NanumGothic"
face.2.src.5.format = "svg"

[webfont:Oswald]
preload = false
face.0.family = "Oswald"
face.0.style = "normal"
face.0.weight = "200"
face.0.display = "swap"
face.0.src.0.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-200.eot"
face.0.src.1.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-200.eot?#iefix"
face.0.src.1.format = "embedded-opentype"
face.0.src.2.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-200.woff2"
face.0.src.2.format = "woff2"
face.0.src.3.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-200.woff"
face.0.src.3.format = "woff"
face.0.src.4.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-200.ttf"
face.0.src.4.format = "truetype"
face.0.src.5.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-200.svg#Oswald"
face.0.src.5.format = "svg"

face.1.family = "Oswald"
face.1.style = "normal"
face.1.weight = "300"
face.1.display = "swap"
face.1.src.0.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-300.eot"
face.1.src.1.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-300.eot?#iefix"
face.1.src.1.format = "embedded-opentype"
face.1.src.2.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-300.woff2"
face.1.src.2.format = "woff2"
face.1.src.3.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-300.woff"
face.1.src.3.format = "woff"
face.1.src.4.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-300.ttf"
face.1.src.4.format = "truetype"
face.1.src.5.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-300.svg#Oswald"
face.1.src.5.format = "svg"

face.2.family = "Oswald"
face.2.style = "normal"
face.2.weight = "400"
face.2.display = "swap"
face.2.src.0.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-regular.eot"
face.2.src.1.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-regular.eot?#iefix"
face.2.src.1.format = "embedded-opentype"
face.2.src.2.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-regular.woff2"
face.2.src.2.format = "woff2"
face.2.src.3.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-regular.woff"
face.2.src.3.format = "woff"
face.2.src.4.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-regular.ttf"
face.2.src.4.format = "truetype"
face.2.src.5.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-regular.svg#Oswald"
face.2.src.5.format = "svg"

face.3.family = "Oswald"
face.3.style = "normal"
face.3.weight = "500"
face.3.display = "swap"
face.3.src.0.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-500.eot"
face.3.src.1.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-500.eot?#iefix"
face.3.src.1.format = "embedded-opentype"
face.3.src.2.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-500.woff2"
face.3.src.2.format = "woff2"
face.3.src.3.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-500.woff"
face.3.src.3.format = "woff"
face.3.src.4.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-500.ttf"
face.3.src.4.format = "truetype"
face.3.src.5.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-500.svg#Oswald"
face.3.src.5.format = "svg"

face.4.family = "Oswald"
face.4.style = "normal"
face.4.weight = "600"
face.4.display = "swap"
face.4.src.0.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-600.eot"
face.4.src.1.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-600.eot?#iefix"
face.4.src.1.format = "embedded-opentype"
face.4.src.2.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-600.woff2"
face.4.src.2.format = "woff2"
face.4.src.3.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-600.woff"
face.4.src.3.format = "woff"
face.4.src.4.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-600.ttf"
face.4.src.4.format = "truetype"
face.4.src.5.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-600.svg#Oswald"
face.4.src.5.format = "svg"

face.5.family = "Oswald"
face.5.style = "normal"
face.5.weight = "700"
face.5.display = "swap"
face.5.src.0.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-700.eot"
face.5.src.1.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-700.eot?#iefix"
face.5.src.1.format = "embedded-opentype"
face.5.src.2.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-700.woff2"
face.5.src.2.format = "woff2"
face.5.src.3.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-700.woff"
face.5.src.3.format = "woff"
face.5.src.4.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-700.ttf"
face.5.src.4.format = "truetype"
face.5.src.5.url = "/assets/fonts/oswald-v49/oswald-v49-latin-ext_latin_cyrillic-ext_cyrillic-700.svg#Oswald"
face.5.src.5.format = "svg"

[webfont:Schibsted Grotesk]
preload = false
face.0.family = "Schibsted Grotesk"
face.0.style = "normal"
face.0.weight = "400"
face.0.display = "swap"
face.0.src.0.url = "/assets/fonts/Schibsted_Grotesk/static/SchibstedGrotesk-Regular.ttf"
face.0.src.0.format = "truetype"

face.1.family = "Schibsted Grotesk Medium"
face.1.style = "normal"
face.1.weight = "500"
face.1.display = "swap"
face.1.src.0.url = "/assets/fonts/Schibsted_Grotesk/static/SchibstedGrotesk-Medium.ttf"
face.1.src.0.format = "truetype"

face.2.family = "Schibsted Grotesk Bold"
face.2.style = "normal"
face.2.weight = "700"
face.2.display = "swap"
face.2.src.0.url = "/assets/fonts/Schibsted_Grotesk/static/SchibstedGrotesk-Bold.ttf"
face.2.src.0.format = "truetype"

face.3.family = "Schibsted Grotesk Bold Italic"
face.3.style = "italic"
face.3.weight = "700"
face.3.display = "swap"
face.3.src.0.url = "/assets/fonts/Schibsted_Grotesk/static/SchibstedGrotesk-BoldItalic.ttf"
face.3.src.0.format = "truetype"

[icon:fontawesome]
preload = true
url = "/assets/libs/fontawesome-free-7.1.0-web/webfonts/fa-solid-900.woff2"
css = "/assets/libs/fontawesome-free-7.1.0-web/css/all.min.css"

[icon:bootstrap-icons]
preload = true
url = "/assets/libs/bootstrap-icons-1.13.1/font/fonts/bootstrap-icons.woff2?e34853135f9e39acf64315236852cd5a"
css = "/assets/libs/bootstrap-icons-1.13.1/font/bootstrap-icons.min.css"
